version: 0.2

phases:
  install:
    commands:
      - echo "Installing backend dependencies"
      - cd app-tier && npm install && cd ..
      - echo "Installing frontend dependencies"
      - cd web-tier && npm install && cd ..
  build:
    commands:
      - echo "Building backend"
      - cd app-tier && npm run build || echo "No build step for backend" && cd ..
      - echo "Building frontend"
      - cd web-tier && npm run build && cd ..
artifacts:
  files:
    - app-tier/**/*
    - web-tier/**/*
    - web-tier/nginx.conf
